name: Test
on:
  repository_dispatch:
    types : [run-test]
  pull_request:
    types: [opened]
  workflow_dispatch :
  push :
    branches:    
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses : ZscalerCWP/Zscaler-IaC-Action@v1.4.0
        id : iac-scan
        with:
          client_id : ${{ secrets.ZSCANNER_CLIENT_ID }}
          client_secret : ${{ secrets.ZSCANNER_CLIENT_SECRET }}
          fail_build : 'true'
          output_format : 'human+github-sarif'
          log_level : 'debug'
          region : 'US'
      - run : echo ${{ steps.iac-scan.outputs.sarif_file_path }}
      - name: Upload SARIF file
        if: ${{ steps.zscaler-iac-scan.outputs.sarif_file_path != '' }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.zscaler-iac-scan.outputs.sarif_file_path }}
